### ISSUE TITLE
qbcore error

### ISSUE THREAD

**Issue by FurmaZ** [AbstractBunny/Bunnys-TaserCartridges#1]
![image](https://user-images.githubusercontent.com/69918985/204618058-7c0289f8-d2f1-4a4b-8b3a-bf53cf589fc7.png)
![image](https://user-images.githubusercontent.com/69918985/204618104-20fbfddc-b5ba-4ba5-aa88-14c8fc90b4f2.png)
![image](https://user-images.githubusercontent.com/69918985/204618141-dc58f2c7-fafd-4691-85a4-966a71f8e974.png)

Any help would be highly appreciated

**Comment by Blayzeisnotavailable** [comment]
local QBCore = exports['qb-core']:GetCoreObject()

put this at the top of ignore.lua
