### ISSUE TITLE
help please 

### ISSUE THREAD

**Issue by gbandzz** [AbstractBunny/Bunnys-TaserCartridges#2]
![image_2023-02-22_164249880](https://user-images.githubusercontent.com/95923239/220765929-7a0d2382-3549-4027-bd47-f3d005f64b30.png)
cartridges dont work and im getting this error 
 also any way i can get rid of this bar 
![image_2023-02-22_164336181](https://user-images.githubusercontent.com/95923239/220766081-723e7774-62cc-4d31-baa3-bedd176bb8f0.png)

any help would be appreciated

**Comment by YungT-SevsideRP** [comment]
and also you have to create new ammo type in qb-weapons/server/main.lua

**Comment by NartioxIms** [comment]
How to do ?

**Comment by NartioxIms** [comment]
You have discord for support ?
